// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/handler.go

// Package mock_http is a generated GoMock package.
package mock_http

import (
	domain "ab180/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockShortLinkRepo is a mock of ShortLinkRepo interface.
type MockShortLinkRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShortLinkRepoMockRecorder
}

// MockShortLinkRepoMockRecorder is the mock recorder for MockShortLinkRepo.
type MockShortLinkRepoMockRecorder struct {
	mock *MockShortLinkRepo
}

// NewMockShortLinkRepo creates a new mock instance.
func NewMockShortLinkRepo(ctrl *gomock.Controller) *MockShortLinkRepo {
	mock := &MockShortLinkRepo{ctrl: ctrl}
	mock.recorder = &MockShortLinkRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortLinkRepo) EXPECT() *MockShortLinkRepoMockRecorder {
	return m.recorder
}

// CreateShortLink mocks base method.
func (m *MockShortLinkRepo) CreateShortLink(ctx context.Context, shortID domain.ShortLink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShortLink", ctx, shortID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateShortLink indicates an expected call of CreateShortLink.
func (mr *MockShortLinkRepoMockRecorder) CreateShortLink(ctx, shortID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShortLink", reflect.TypeOf((*MockShortLinkRepo)(nil).CreateShortLink), ctx, shortID)
}

// GetURLByShortLink mocks base method.
func (m *MockShortLinkRepo) GetURLByShortLink(ctx context.Context, shortLink string) (domain.ShortLink, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetURLByShortLink", ctx, shortLink)
	ret0, _ := ret[0].(domain.ShortLink)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetURLByShortLink indicates an expected call of GetURLByShortLink.
func (mr *MockShortLinkRepoMockRecorder) GetURLByShortLink(ctx, shortLink interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetURLByShortLink", reflect.TypeOf((*MockShortLinkRepo)(nil).GetURLByShortLink), ctx, shortLink)
}
